[tool.poetry]
name = "osint-shared"
version = "0.1.0"
description = "OSINT Platform Shared Library"
authors = ["OSINT Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
